//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.20 at 02:47:50 ���� CST 
//


package com.gbcom.system.domain.bean.column;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isValid" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isGridShow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="gridName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gridWidth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "columnParam")
public class ColumnParam {

    @XmlAttribute(required = true)
    protected String column;
    @XmlAttribute
    protected String formId;
    @XmlAttribute
    protected String formName;
    @XmlAttribute
    protected String key;
    @XmlAttribute
    protected Boolean isValid;
    @XmlAttribute
    protected Boolean isGridShow;
    @XmlAttribute
    protected String gridName;
    @XmlAttribute
    protected String gridWidth;
    @XmlAttribute
    protected Boolean isExpired;

    /**
     * Gets the value of the column property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the formId property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getFormId() {
        return formId;
    }

    /**
     * Sets the value of the formId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFormId(String value) {
        this.formId = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the isValid property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * Sets the value of the isValid property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsValid(Boolean value) {
        this.isValid = value;
    }

    /**
     * Gets the value of the isGridShow property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean getIsGridShow() {
        return isGridShow;
    }

    /**
     * Sets the value of the isGridShow property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsGridShow(Boolean value) {
        this.isGridShow = value;
    }

    /**
     * Gets the value of the gridName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * Sets the value of the gridName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGridName(String value) {
        this.gridName = value;
    }

    /**
     * Gets the value of the gridWidth property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getGridWidth() {
        return gridWidth;
    }

    /**
     * Sets the value of the gridWidth property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGridWidth(String value) {
        this.gridWidth = value;
    }

    /**
     * isExpired
     * @return isExpired
     */
    public Boolean getIsExpired() {
        return isExpired;
    }

    /**
     * 
     * @param expired isExpired
     */
    public void setIsExpired(Boolean expired) {
        this.isExpired = expired;
    }

    /**
     * 
     * @return formName
     */
    public String getFormName() {
        return formName;
    }

    /**
     * 
     * @param formName formName
     */
    public void setFormName(String formName) {
        this.formName = formName;
    }
}
